export * from './movieInterface';
export * from './movieResInterface';
export * from './posterResInterface';
export * from './genreInterface';
export * from './genreResInterface';
export * from './searchInterface';
export * from './videoInterface';
export * from './reviewInterface';
export * from './reviewResInterface';